AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - config/**/*
    - bin/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 80

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
