version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
        - PGHOST: 127.0.0.1
      - image: circleci/postgres:9.4
        environment:
        - POSTGRES_USER=postgres

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing application dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Creating database
          command: bundle exec rake db:create
      - run:
          name: Initializing database
          command: bundle exec rake db:schema:load

      # Run tests!
      - run:
          name: Running tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)"
            bin/rails test "${TEST_FILES}"

      # Collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
