version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
        - PGHOST: 127.0.0.1
      - image: circleci/postgres:9.4
        environment:
        - POSTGRES_USER=postgres

    working_directory: ~/repo

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Bundle install dependencies
      - run:
          name: Installing application dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Creating database
          command: bundle exec rake db:create
      - run:
          name: Initializing database
          command: bundle exec rake db:schema:load

      # Run rspec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

