development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fresh_pots_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: fresh_pots_production
